Removed homebrew from error message

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -22,6 +22,12 @@ install_php() {
 
   local operating_system=$(uname -a)
 
+      echo "test2"
+    echo $(locate libpng)
+    echo $(locate libjpeg)
+    exit 1
+
+
   # many macos packages require modifications to various env variables in order for the build process to pick
   # up the correct version of the packages. These checks are done here instead of `construct_configure_options`
   # because modifications to $PKG_CONFIG_PATH are not propogated from the subshell to this shell.
@@ -76,7 +82,7 @@ install_php() {
     fi
 
     if [ -n "$missing_required_packages" ]; then
-      echo "Required packages are missing, install via homebrew: $missing_required_packages"
+      echo "Required packages are missing: $missing_required_packages"
       exit 1
     fi
   fi
@@ -335,6 +341,10 @@ os_based_configure_options() {
       missing_required_packages="$missing_required_packages libiconv"
     fi
   else
+    echo "test"
+    echo $(locate libpng)
+    echo $(locate libjpeg)
+    exit 1
     local jpeg_path=$(locate libjpeg | awk '{ print length(), $0 | "sort -n" }' | cut -d" " -f2- | head -n 1)
     local libpng_path=$(locate libpng | awk '{ print length(), $0 | "sort -n" }' | cut -d" " -f2- | head -n 1)
     configure_options="--with-openssl --with-curl --with-zlib --with-readline --with-gettext"
@@ -353,7 +363,7 @@ os_based_configure_options() {
   fi
 
   if [ -n "$missing_required_packages" ]; then
-    echo "Required packages are missing, install via homebrew: $missing_required_packages"
+    echo "Required packages are missing: $missing_required_packages"
     exit 1
   fi
 
